services:
  db:
    image: postgres:18
    container_name: expriment-db
    restart: always

    environment:  
      POSTGRES_USER: sandeep-postgresql
      POSTGRES_PASSWORD: sandeep-pass-postgresql
      POSTGRES_DB: sandeep-db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
