CREATE TABLE  booksStore (
    id SERIAL PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL,
    author VARCHAR(50) NOT NULL, 
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);